### ISSUE TITLE
Answer Input Field is Missing

### ISSUE THREAD

**Issue by nchathu2014** [BM-BrunoMarques/mobile-flashcards#1]
As per specification, Question view should have a form with the two input field which is question and answer, both fields should be editable or the user should able to give input. In the current implementation, the answer input field is missing.

**Comment by BM-BrunoMarques** [comment]
> As per specification, Question view should have a form with the two input field which is question and answer, both fields should be editable or the user should able to give input. In the current implementation, the answer input field is missing.

according with the specification, which is:
"The New Question view includes a form with fields for a question and answer, and a submit button.
Submitting the form correctly adds the question to the deck."

The Question view has 3 elements, the input text field for the Question, the input switch field for the Answer. and the Submit button.

In my project the answer input should be a Switch button field, which you can toggle as 'Incorrect' or 'Correct'. I believe this is the right way to do so, since in the **specification for the Quiz page** it is required that:
**"Buttons are included to allow the student to mark their guess as 'Correct' or 'Incorrect'"**

Is this switch button not showing?
![image](https://user-images.githubusercontent.com/37351917/104082887-c7bc3a00-51ee-11eb-8a1c-56c1763dcd48.png)

**if so, to easily address the bug, may I know in which platform was the problem reproduced?**

**Comment by nchathu2014** [comment]
In the Rubric, they asking,


Does the New Question view function correctly? 
The New Question view includes a form with **fields for a question and answer**, and a submit button.Submitting the form correctly adds the question to the deck.

But they are not mentioned fields should be TextInputs,  Question is a TextInput, but answer is a SlideToggle input.

My reviwer saying, there should be Two TextInputs but as you explain my reviewer is wrong.

Is that correct?

Thank You
Nuwan

**Comment by BM-BrunoMarques** [comment]
> In the Rubric, they asking,
> 
> Does the New Question view function correctly?
> The New Question view includes a form with **fields for a question and answer**, and a submit button.Submitting the form correctly adds the question to the deck.
> 
> But they are not mentioned fields should be TextInputs, Question is a TextInput, but answer is a SlideToggle input.
> 
> My reviwer saying, there should be Two TextInputs but as you explain my reviewer is wrong.
> 
> Is that correct?
> 
> Thank You
> Nuwan


Ok I took a completely different approach. I thought that it was asked to create true or false questions for you to answer later. 
So I am storing the answer as 'Correct' or 'Incorrect'. My project passed as it is, so I never took a second thought about it.

What the reviewer is asking to do is save the question and the answer as text fields. Then, in the Quiz you just increment 'Correct' or 'Incorrect', without checking anything else. 
Sounds like this is supposed to be a memory test. So it's up to the user to choose if he was right or wrong about his guess, after seeing the answer.

**So this is still a valid project because they did not specify they wanted an 'input text field' for the answer. Even though it changes the logic of the Quiz completely. It's still following the required specifications and you can reason with the reviewer that indeed everything fits the criteria.**

I will correct my version asap though, since it's creating some confusion and I want people to be able to keep using this as a base for their project, thank you for pointing it out!

**Comment by nchathu2014** [comment]
Hi Bruno, 
Aslo they are mentioning that After Creating a Deck, automatic navigation to the Home View is required. For the moment, After creating it is in the same view.

Thank You,
Nuwan

**Comment by BM-BrunoMarques** [comment]
> Hi Bruno,
> Aslo they are mentioning that After Creating a Deck, automatic navigation to the Home View is required. For the moment, After creating it is in the same view.
> 
> Thank You,
> Nuwan

this issue has been resolved now :)

**About the original issue**
I thank you for pointing this out, but since it still follows the specification required and being already more complex than what the reviewer is asking for, I will not change my project. I will leave a note in the README section, so people are aware that this project has taken an unusual but still valid approach as per what is required in the specification.
